task: detection

num_classes: 5
# return_mask: False
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: VisdroneVehicleDetection
    img_folder: /root/autodl-tmp/code/VOC_dateset/VisDroneVehicle/train/images/
    ann_file: /root/autodl-tmp/code/VOC_dateset/VisDroneVehicle/annotations/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 32
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: VisdroneVehicleDetection
    img_folder: /root/autodl-tmp/code/VOC_dateset/VisDroneVehicle/val/images/
    ann_file: /root/autodl-tmp/code/VOC_dateset/VisDroneVehicle/annotations/val.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False