
__include__: [
  '../dataset/SODA-A_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd_goldfusion.yml',
]


output_dir: ./output/rtdetr_r18vd_goldfusion_6x_SODAA



PResNet:
  depth: 18
  return_idx: [0, 1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  pretrained: True

Gold_HybridEncoder:
  in_channels: [64, 128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100



optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

